name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: xml

    - name: Install dependencies
      run: composer install

    - name: Set permissions for PHPUnit
      run: chmod +x vendor/bin/phpunit

    - name: Validate PHP syntax
      run: php -l index.php

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit tests/
